const mongoose = require("mongoose");

const admissionApplicationSchema = new mongoose.Schema(
  {
    childName: { type: String, required: true },
    applicationNumber: { type: String, unique: true, sparse: true },
    dob: { type: String, required: true },
    age: { type: Number, required: true },
    sex: { type: String, enum: ["Female", "Male"], required: true },
    homeAddress: { type: String, required: true },
    stateOfOrigin: { type: String, required: true },
    lga: { type: String, required: true },
    religion: String,
    churchAttending: String,
    bloodGroup: String,
    genotype: String,
    classSought: { type: String, required: true },
    numberOfChildren: Number,
    childPosition: String,
    allergies: String,
    immunizationUpToDate: { type: String, enum: ["Yes", "No"], required: true },
    hasMedicalCondition: { type: String, enum: ["Yes", "No"], required: true },
    medicalDetails: String,
    fatherName: String,
    fatherOccupation: String,
    fatherOfficeAddress: String,
    motherName: String,
    motherOccupation: String,
    motherOfficeAddress: String,
    primaryPhone: { type: String, required: true },
    parentEmail: { type: String, required: true },
    communicationPreferences: [{ type: String, enum: ["Phone", "Text", "Email"] }],
    emergencyContactName: { type: String, required: true },
    emergencyContactPhone: { type: String, required: true },
    pickupOneName: { type: String, required: true },
    pickupOnePhone: { type: String, required: true },
    pickupOneAddress: String,
    pickupTwoName: String,
    pickupTwoPhone: String,
    pickupTwoAddress: String,
    attestationName: { type: String, required: true },
    attestationDate: { type: String, required: true },
    attestationAgreement: { type: Boolean, default: false },
    paymentReference: String,
    payment: { type: mongoose.Schema.Types.ObjectId, ref: "AdmissionPayment" },
    paymentAmountKobo: Number,
    paymentCurrency: String,
    paymentPaidAt: Date,
    admissionDocuments: [{
      label: String,
      field: String,
      originalName: String,
      mimetype: String,
      size: Number,
      url: String,
      publicId: String,
      resourceType: String,
      uploadedAt: { type: Date, default: Date.now }
    }],
    isRead: { type: Boolean, default: false }
  },
  { timestamps: true }
);

module.exports = mongoose.model("AdmissionApplication", admissionApplicationSchema);
